import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

// components
import ManualHeader from '../components/manualHeader'
import Header from '../components/header'
import LotteryEntrance from '../components/lotteryEntrance'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Smart Contract Lottery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      { /** header / connect button / nav bar */}
      {/* <ManualHeader></ManualHeader> */}
      <Header></Header>

      <main className={styles.main}>
        Hello World 
        <LotteryEntrance></LotteryEntrance>
      </main>

    


      {/* footer */}
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
